version: "3.9"
services:
  server:
    build:
      target: dev-service
    command: make run-server-reload
    volumes:
      - "../:/workspace"
    env_file: [../config/dev.env]
  worker:
    build:
      target: dev-service
    command: make run-worker-reload
    volumes:
      - "../:/workspace"
    env_file: [../config/dev.env]
