version: "3.9"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
volumes:
  my-db:
  cache:
