version: "3.9"
services:
  server:
    build:
      target: release
    command: ./entrypoint/server.sh
    env_file: [../.env, ../config/release.env, ../config/docker.env]
  worker:
    build:
      target: release
    command: ./entrypoint/worker.sh
    env_file: [../.env, ../config/release.env, ../config/docker.env]
