version: "3.9"
services:
  server:
    build:
      context: ../
    ports:
      - 8000:8000
    env_file: [../.env, ../config/docker.env]
  worker:
    build:
      context: ../
    env_file: [../.env, ../config/docker.env]